# Generated by Django 5.1.6 on 2025-05-16 10:43

import datacore.models.schemas
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='schema/attribute title')),
                ('name', models.SlugField(help_text='Internal short label for schema,containing only letters, numbers, underscores or hyphens', max_length=32, unique=True, verbose_name='schema name')),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('field_type', datacore.models.schemas.MarshmallowField(choices=[(2, 'Boolean'), (4, 'Date'), (5, 'DateTime'), (6, 'Decimal'), (7, 'Dict'), (8, 'Email'), (9, 'Enum'), (10, 'Float'), (12, 'Int'), (13, 'Integer'), (14, 'IP'), (15, 'IPInterface'), (17, 'Mapping'), (21, 'String'), (22, 'Time'), (23, 'TimeDelta'), (25, 'URL'), (26, 'UUID')], verbose_name='Field type')),
                ('is_multiple', models.BooleanField(default=False, help_text='If True, values are treated as a list.', verbose_name='is multiple')),
                ('schema', models.JSONField(blank=True, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='schema')),
            ],
            options={
                'verbose_name': '\u200aData scema',
                'verbose_name_plural': '\u200aData schemas',
                'ordering': ['name'],
                'unique_together': {('name', 'version')},
            },
        ),
    ]
